// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfbyllxaxyedjjadgobv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmYnlsbHhheHllZGpqYWRnb2J2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5NjE5ODYsImV4cCI6MjA3NzUzNzk4Nn0.hOB1seKnmNM_os6B-dohl2gpamKPf8ECmWLP0NejaU8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});